/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import DAO.AdministradorDAO;
import DAO.EmailSender;
import DAO.FuncionarioDAO;
import Util.CodigoCache;
import Util.Converter;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class TelaRedefinirSenha extends javax.swing.JInternalFrame {
private Timer timer;
private int tempoRestante = 30;
    /**
     * Creates new form TelaRedefinirSenha
     */
    public TelaRedefinirSenha() {
        initComponents();
        estilizarComponentes();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btn_enviarcodigo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_redefinirsenha = new javax.swing.JButton();
        txtNovaSenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Email");

        btn_enviarcodigo.setText("Enviar Código");
        btn_enviarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarcodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite o Código");

        jLabel3.setText("Nova Senha");

        jLabel4.setText("Confirmar Senha");

        btn_redefinirsenha.setText("Redefinir Senha");
        btn_redefinirsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redefinirsenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNovaSenha))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo)
                                .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_enviarcodigo)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_redefinirsenha)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enviarcodigo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_redefinirsenha)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarcodigoActionPerformed

    String email = txtEmail.getText().trim();
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe seu e-mail para enviar o código.");
        txtEmail.requestFocus();
        return;
    }

    // Verificar se o e-mail existe em algum dos cadastros
    FuncionarioDAO funcDao = new FuncionarioDAO();
    AdministradorDAO admDao = new AdministradorDAO();

    boolean emailExiste = funcDao.emailExiste(email) || admDao.emailExiste(email);

    if (!emailExiste) {
        JOptionPane.showMessageDialog(this, "E-mail não encontrado no sistema.");
        return;
    }

    // Gerar código aleatório
    String codigo = Converter.gerarCodigo(6);

    // Enviar e-mail
    EmailSender.enviarCodigo(email, codigo);

    // Salvar no cache
    CodigoCache.salvarCodigo(email, codigo);

    JOptionPane.showMessageDialog(this, "Código enviado para o e-mail informado.");

    tempoRestante = 30;  // reseta o contador
timer = new Timer(1000, e -> {
    if (tempoRestante > 0) {
        btn_enviarcodigo.setText("Reenviar em " + tempoRestante + "s");
        tempoRestante--;
    } else {
        timer.stop();
        btn_enviarcodigo.setText("Enviar Código");
        btn_enviarcodigo.setEnabled(true);
    }
});
timer.start();
    }//GEN-LAST:event_btn_enviarcodigoActionPerformed

    private void btn_redefinirsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redefinirsenhaActionPerformed
 String email = txtEmail.getText().trim();
                String codigoDigitado = txtCodigo.getText().trim();
                String novaSenha = new String(txtNovaSenha.getPassword()).trim();
                String confirmarSenha = new String(txtConfirmarSenha.getPassword()).trim();

                if (email.isEmpty() || codigoDigitado.isEmpty() || novaSenha.isEmpty() || confirmarSenha.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
                    return;
                }

                if (!novaSenha.equals(confirmarSenha)) {
                    JOptionPane.showMessageDialog(null, "As senhas não coincidem.");
                    return;
                }

                if (!CodigoCache.validarCodigo(email, codigoDigitado)) {
                    JOptionPane.showMessageDialog(null, "Código inválido.");
                    return;
                }

                FuncionarioDAO funcDao = new FuncionarioDAO();
                AdministradorDAO admDao = new AdministradorDAO();

                boolean sucesso = funcDao.atualizarSenhaPorEmail(email, novaSenha);
                if (!sucesso) {
                    sucesso = admDao.atualizarSenhaPorEmail(email, novaSenha);
                }

                if (sucesso) {
                    JOptionPane.showMessageDialog(null, "Senha redefinida com sucesso.");
                    CodigoCache.limparCodigo(email);
                    dispose(); // fecha a janela
                } else {
                    JOptionPane.showMessageDialog(null, "E-mail não encontrado.");
                }
            
    }//GEN-LAST:event_btn_redefinirsenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviarcodigo;
    private javax.swing.JButton btn_redefinirsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNovaSenha;
    // End of variables declaration//GEN-END:variables


private void estilizarComponentes() {
    // Fontes e cores
    Font labelFont = new Font("Segoe UI", Font.PLAIN, 14);
    Color labelColor = new Color(60, 63, 65); // cinza escuro

    jLabel1.setFont(labelFont);
    jLabel1.setForeground(labelColor);
    jLabel2.setFont(labelFont);
    jLabel2.setForeground(labelColor);
    jLabel3.setFont(labelFont);
    jLabel3.setForeground(labelColor);
    jLabel4.setFont(labelFont);
    jLabel4.setForeground(labelColor);

    Font fieldFont = new Font("Segoe UI", Font.PLAIN, 14);
    txtEmail.setFont(fieldFont);
    txtCodigo.setFont(fieldFont);
    txtNovaSenha.setFont(fieldFont);
    txtConfirmarSenha.setFont(fieldFont);

    btn_enviarcodigo.setFont(new Font("Segoe UI", Font.BOLD, 14));
    btn_enviarcodigo.setBackground(new Color(70, 130, 180));
    btn_enviarcodigo.setForeground(Color.WHITE);
    btn_enviarcodigo.setFocusPainted(false);

    btn_redefinirsenha.setFont(new Font("Segoe UI", Font.BOLD, 14));
    btn_redefinirsenha.setBackground(new Color(34, 139, 34));
    btn_redefinirsenha.setForeground(Color.WHITE);
    btn_redefinirsenha.setFocusPainted(false);
}


}
