/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import JDBC.ConnectionFactory;
import Objs.Sessao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class TelaLogin extends javax.swing.JInternalFrame {
 // Instância da tela principal
    private TelaPrincipal2 telaPrincipal;

Connection conecta = null;
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin(TelaPrincipal2 principal) {
        initComponents();
        
         this.telaPrincipal = principal; // ← usar o parâmetro recebido
         jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26));
jLabel3.setForeground(new java.awt.Color(30, 30, 70)); // Título azul escuro

txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14));
txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 14));



SwingUtilities.invokeLater(() -> {
    getContentPane().requestFocusInWindow(); // Ou outro componente qualquer
    
     // Após a janela ser carregada, desativa a máscara
    SwingUtilities.invokeLater(() -> {
        txtSenha.setEchoChar((char) 0); // Agora funciona!
    });
});

    }
    
    private class Usuario {
    String nome;
    String tipo; // "ADM" ou "FUNC"
}


   private Usuario validarLogin() {
    String usuario = txtEmail.getText(); // Agora é o campo de USUÁRIO, não e-mail
    String senha = new String(txtSenha.getPassword());

    try {
        conecta = new ConnectionFactory().conecta();

        // Tentar encontrar usuário na tabela de administradores
        String sqlAdm = "SELECT adm_nome FROM tb_adm WHERE BINARY adm_usuario = ? AND BINARY senha = ?";
        PreparedStatement stmtAdm = conecta.prepareStatement(sqlAdm);
        stmtAdm.setString(1, usuario);
        stmtAdm.setString(2, senha);
        ResultSet rsAdm = stmtAdm.executeQuery();

        if (rsAdm.next()) {
            Usuario user = new Usuario();
            user.nome = rsAdm.getString("adm_nome");
            user.tipo = "ADM";
            conecta.close();
            return user;
        }

        // Se não for admin, tentar funcionário
        String sqlFunc = "SELECT fun_nome FROM tb_funcionario WHERE BINARY fun_usuario = ? AND BINARY fun_senha = ?";
        PreparedStatement stmtFunc = conecta.prepareStatement(sqlFunc);
        stmtFunc.setString(1, usuario);
        stmtFunc.setString(2, senha);
        ResultSet rsFunc = stmtFunc.executeQuery();

        if (rsFunc.next()) {
            Usuario user = new Usuario();
            user.nome = rsFunc.getString("fun_nome");
            user.tipo = "FUNC";
            conecta.close();
            return user;
        }

        conecta.close();
        return null; // usuário não encontrado

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao validar login: " + e.getMessage());
        return null;
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_logar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_esquecisenha = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Usuario");

        jLabel2.setText("Senha");

        txtEmail.setForeground(new java.awt.Color(128, 128, 128));
        txtEmail.setText("Digite seu Nome de Usuario....");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtSenha.setForeground(new java.awt.Color(128, 128, 128));
        txtSenha.setText("Digite sua senha");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        btn_logar.setBackground(new java.awt.Color(215, 32, 98));
        btn_logar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_logar.setForeground(new java.awt.Color(255, 255, 255));
        btn_logar.setText("ENTRAR");
        btn_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mulher salão1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        btn_esquecisenha.setBackground(new java.awt.Color(215, 32, 98));
        btn_esquecisenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_esquecisenha.setForeground(new java.awt.Color(255, 255, 255));
        btn_esquecisenha.setText("ESQUECI MINHA SENHA");
        btn_esquecisenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esquecisenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_esquecisenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_logar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btn_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_esquecisenha)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logarActionPerformed
   Usuario usuario = validarLogin();

    if (usuario != null) {
        // Guardar na sessão
        Sessao.tipoUsuario = usuario.tipo;
        Sessao.nomeUsuario = usuario.nome;

        JOptionPane.showMessageDialog(this, "Bem-vindo, " + usuario.nome + "!");

        if ("ADM".equals(usuario.tipo)) {
            telaPrincipal.habilitarMenusAdministrador();
        } else if ("FUNC".equals(usuario.tipo)) {
            telaPrincipal.habilitarMenusFuncionario();
        }

        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Nome de Usuário ou senha inválidos.");
    }

    }//GEN-LAST:event_btn_logarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if (txtEmail.getText().equals("Digite seu Nome de Usuario....")) {
    txtEmail.setText("");
    txtEmail.setForeground(Color.BLACK);
}

    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (txtEmail.getText().isEmpty()) {
    txtEmail.setText("Digite seu Nome de Usuario....");
    txtEmail.setForeground(Color.GRAY);
}

    }//GEN-LAST:event_txtEmailFocusLost

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
         if (txtSenha.getPassword().length == 0) {
        txtSenha.setText("Digite sua senha");
        txtSenha.setEchoChar((char) 0); // Mostra texto sem asteriscos
        txtSenha.setForeground(new Color(153, 153, 153)); // Cinza claro
    }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        if (String.valueOf(txtSenha.getPassword()).equals("Digite sua senha")) {
        txtSenha.setText("");
        txtSenha.setEchoChar('•'); // Volta a mostrar como senha
        txtSenha.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void btn_esquecisenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esquecisenhaActionPerformed
           // Percorre os frames internos já abertos
    for (javax.swing.JInternalFrame frame : TelaPrincipal2.jDesktopPane1.getAllFrames()) {
        if (frame instanceof TelaRedefinirSenha) {
            // Se já existe uma instância aberta, apenas foca nela e retorna
            try {
                frame.setSelected(true);
                frame.toFront();
            } catch (java.beans.PropertyVetoException ex) {
                ex.printStackTrace();
            }
            return; // Não abre uma nova
        }
    }

    // Se não encontrou, cria uma nova instância
    TelaRedefinirSenha telaRedefinir = new TelaRedefinirSenha();
    TelaPrincipal2.jDesktopPane1.add(telaRedefinir);
    telaRedefinir.setVisible(true);
    telaRedefinir.setLocation(
        (TelaPrincipal2.jDesktopPane1.getWidth() - telaRedefinir.getWidth()) / 2,
        (TelaPrincipal2.jDesktopPane1.getHeight() - telaRedefinir.getHeight()) / 2
    );
    }//GEN-LAST:event_btn_esquecisenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_esquecisenha;
    private javax.swing.JButton btn_logar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
